name: 鸿博
description: 生活，随笔，记录，旅游，音乐，电影，风景，心情？ 
meta_description: "鸿博, 博客，微博，MicroBlog，湖北，河北，HB"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 8
domain_name: 'https://hbw.me'
google_analytics: 'UA-180937563-1'
# disqus: false
# disqus_shortname: 'your-disqus-shortname'

# https://github.com/gitalk/gitalk#install
gitalk:
    gitalk:
    owner: qinghongjiao
    repo: gitalk
    clientID: 7d4444b91100f1f08ca2
    clientSecret: 25069b7f66d24c87615bff006848ee1b7345b50a

# Details for the RSS feed generator
url:            'https://hbw.me'
author:         '鸿博，HBw.Me'
# authorTwitter:  'YourTwitterUsername'

permalink:       /:title.html

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
